### ISSUE TITLE
Power off after idle for some time.

### ISSUE THREAD

**Issue by lixxbox** [jneilliii/OctoPrint-TasmotaMQTT#12]
Is there a way to turn Sonoff devices off when the printer/octoprint is idle for some time?
Either using an additional plugin, or from TasmotaMQTT directly. If not, could it be implemented?

https://plugins.octoprint.org/plugins/psucontrol/ has such a feature called Idle timeout.

btw. thank you for your great plugins.

**Comment by jneilliii** [comment]
Looks like it wouldn't be too difficult to implement using the same technique psucontrol uses by adding a repeated timer loop.  It may be a while before I can get to it, but will add it to the list for the next round of updates.

**Comment by jneilliii** [comment]
I just thought of something that would accomplish roughly the same thing.  With the latest update the plugin will not power off the relay if `Warn Printing` is enabled and the M81 GCODE command is sent to power off the relay while the printer is still printing. 

So set your relay setting like this:

![image](https://user-images.githubusercontent.com/5249455/41816789-d543463e-775b-11e8-825d-5dc025cc6122.png)

And then in OctoPrint's GCODE Scripts section enter the following, matching the topic and relay number like this:

![image](https://user-images.githubusercontent.com/5249455/41816796-1001bef4-775c-11e8-8488-b548f539cadc.png)

In the above settings this would power off the relay 1800 seconds (30 minutes) after a print job is completed. However, because the `Warn While Printing` option is enabled if you start another print during that 30 minute window the printer will not power off and start the timeout again after that new print job is complete.

**Comment by lixxbox** [comment]
I tested it briefly and it seems to work as you described it. In my opinion it works differently than the PSU Control Plugin. For example, it won't turn off without printing. So I entered the Code Script additionally for "After print job is cancelled" and "After connection to printer is established".

I'm going to test it further.
Thank you!

**Comment by derpicknicker1** [comment]
I tried this solution. In general it works. But when i send the M81 gcode after connection to printer, the display of my Prusa MK3 shows only crab. If i remove the M81 from gcode scripts for "after connected to printer", it will work fine again.

**Comment by jneilliii** [comment]
@derpicknicker1, does it do that if you issue any other command in that setting, maybe try M114?  If that doesn't cause the "crab issue" I think if I add a custom gcode action command instead of using the default M81 command it will resolve this.  I've done that for my other power plugins for one reason or another (mostly klipper support).
