### ISSUE TITLE
State topic changed

### ISSUE THREAD

**Issue by SebDominguez** [jneilliii/OctoPrint-TasmotaMQTT#33]
I believe in the last version of Tasmota the default state topic as changed.
Now I can still turn ON my Sonoff with OctoPrint-TasmotaMQTT, but the icon is spinning indefinitely waiting to get the state back.

I've updated from 6.5.0 to 8.1.0. My Full topic is `%prefix%/%topic%/`and this is exactly what I've put inside OctoPrint-TasmotaMQTT

**Comment by jneilliii** [comment]
On your tasmota set `SetOption26` to `1`, and add the 1 as index.

**Comment by SebDominguez** [comment]
`SetOption26` was already set to `1` (I was using the HTTP variant of your plugin as a workaround and this option needed to be activated)

<img width="507" alt="Capture d’écran 2020-03-04 à 09 30 30" src="https://user-images.githubusercontent.com/52816569/75859715-ccf46f80-5dfa-11ea-9f39-39f3652f963f.png">

`Relay #` was set to `1` I assume this is what you call `index`

<img width="582" alt="Capture d’écran 2020-03-04 à 09 31 26" src="https://user-images.githubusercontent.com/52816569/75859767-eeedf200-5dfa-11ea-9d32-8e031b8ef00f.png">

When I press the button assigned to the `tasmota-3570` the following payload are send to / emitted from my device.

<img width="437" alt="Capture d’écran 2020-03-04 à 09 35 34" src="https://user-images.githubusercontent.com/52816569/75860093-8b17f900-5dfb-11ea-8782-5bb23d73ada6.png">

Unfortunately the `icon-lightbulb` on the OctoPrint main page keep spinning indefinitely.

My `Full Topic` is set to `%prefix%/%topic%/`in OctoPrint-TasmotaMQTT's settings

<img width="704" alt="Capture d’écran 2020-03-04 à 09 41 26" src="https://user-images.githubusercontent.com/52816569/75860581-59ebf880-5dfc-11ea-9d7b-2c178565bc66.png">
 
On my tasmota device I've tried many different `Full Topic` string (since mine isn't the default one) just to see if the was the problem

<img width="356" alt="Capture d’écran 2020-03-04 à 09 44 32" src="https://user-images.githubusercontent.com/52816569/75860835-c23ada00-5dfc-11ea-80d8-6c3c89a93445.png">

Normally I set my `Full Topic` to be `%prefix%/%hostname%/` to get commands like `cmnd/tasmota-3570/POWER` so I don't need to manually set the hostname and I can leave it to the default `%s-%04d`

If I manually set the `topic` variable inside the MQTT settings on tasmota to for instance `tasmota-3570` instead if the `tasmota`default one, then my hostname become `tasmota-3570-3570` I don't know why the `%s` in the hostname get replaced by what is supposed to be `%topic%` in the last version of Tasmota... So I replaced `%topic%` by `%hostname%` inside tasmota settings but this shouldn't make any difference inside OctoPrint-TasmotaMQTT.

Anyway just for sanity reasons I tested setting manually my `topic` to be `tasmota-3570` and my `Full Topic` to `%prefix%/%topic%/` and make sure I have the same string inside OctoPrint-TasmotaMQTT, but same result. I can turn ON a Sonoff, but the status doesn't get read back by OctoPrint-TasmotaMQTT.


![ezgif-3-5206f83cd2cc](https://user-images.githubusercontent.com/52816569/75862432-3e362180-5dff-11ea-96b9-1cc85cb80eea.gif)

**Comment by jneilliii** [comment]
Ok, thanks for the great details. Are there any errors in the logs or your browser's developer console?

**Comment by SebDominguez** [comment]
Nothing that I suspect to be useful

<img width="1529" alt="Capture d’écran 2020-03-04 à 14 06 27" src="https://user-images.githubusercontent.com/52816569/75882459-849c7800-5e21-11ea-868d-5a5094eca818.png">

**Comment by yordanov-alexandar** [comment]
I have the same problem - I can turn the device on but the icon never stops spinning to reflect the state. The device has Tasmota version 6.6.0
I have it configured in Home Assistant too and it's not showing the status there either. The strange thing is that it was showing the status correctly until recently. I can't be sure but i think the problem started after I installed the Tasmota plugin in OctoPrint (https://plugins.octoprint.org/plugins/tasmota/) - no idea how that can interfere. I later decided to remove that plugin and use Tasmota-MQTT because I couldn't use the device in Home Assistant any more and was thinking that the Tasmota plugin may interfere somehow but the problem remains even after I have removed the Tasmota plugin.
From Home Assistant -> Developer Tools -> MQTT I can send ON, OFF and TOGGLE payload to the cmnd/<topic>/POWER and they are working turning on and off the device. I can also listen to a topic so I tried listening to stat/<topic>/POWER but it's always returning OFF.
My best guess is that the Tasmota plugin made some changes to the device settings but I have no idea what...

**Comment by SebDominguez** [comment]
I personally doesn't have any problem reading back the stat from other software. I use Node-RED / Homebridge

![ezgif-3-1772c8542b2f](https://user-images.githubusercontent.com/52816569/75923682-e383e080-5e65-11ea-8439-a9a3dc39907d.gif)


Make sure that in Home Assistant you are reading back the `stat` from the `POWER1` topic if you have the `SetOption26` enabled.

For instance if your `%topic%` is set to `sonoff_0042` and `SetOption26`is set to `1` your sonoff will publish back the state in `stat/sonoff_0042/POWER1`

To check if `SetOption26` is enabled, log into the web GUI of your sonoff, then go to `console` and just type `SetOption26` in the text box and hit enter.

Tasmota will respond you `22:11:43 MQT: stat/sonoff_0042/RESULT = {"SetOption26":"ON"}` if the option is enabled.

To disabled it simply type `SetOption26 0`

You can find more about those SetOption [here](https://github.com/arendst/Tasmota/wiki/Commands#setoption-overview)

**Comment by yordanov-alexandar** [comment]
That solved my problem. The state is now read everywhere correctly. Thank you
The SetOption26 value was ON. I am pretty sure I never touched that setting and since I could turn ON and OFF the device from cmnd/topic/POWER without adding 1 I assumed it was still OFF and didn't check.
Is it possible that the Tasmota plugin changed that setting?

**Comment by SebDominguez** [comment]
I don't know what is the "Tasmota" plugin but [OctoPrint-Tasmota](https://github.com/jneilliii/OctoPrint-Tasmota) will detect if `SetOption26` is not enabled. Since the option need to be activated for this particular plugin it will prompt you if you want to activate it automatically.

**Comment by yordanov-alexandar** [comment]
Yes that's the plugin. I must have pressed ok and forgotten about it :)
Anyway thanks for the help

**Comment by jneilliii** [comment]
So I went back and reviewed the code and I think after changing the topic/relay # in the plugin's settings to match the topic being subscribed to then you have to restart OctoPrint because the subscriptions are created on startup of the OctoPrint server. So if SetOption26 is enabled and you enter the Relay # of 1 in the plugin's settings and then restart OctoPrint it should in theory work.

If that is true then I can fix this by checking against changes in the relay configs between saves and re-subscribe to the correct topics.

**Comment by biga888** [comment]
I was having difficulties with using this plugin on a Sonoff S31 plug. It would turn off and the icon would spin as described above. SetOption26 was off, so I tried turning it on and things seemed to work properly, but then the plug was not working in Home Assistant. I then SetOption26 to off and everything is working like it should with OctoPrint and Home Assistant. Seemed SetOption26 needed to be toggled on and off to make things work?
